
// ENV vars for gateway processing
var APIMANAGER='APIMANAGER';
var APIMANAGER_PORT='APIMANAGER_PORT';
var CONFIGDIR='CONFIG_DIR';
var DATASTORE_PORT='DATASTORE_PORT';
var APIMANAGER_CATALOG='APIMANAGER_CATALOG';
var GW_PUBLIC_KEY='GW_PUBLIC_KEY';
var GW_PRIVATE_KEY='GW_PRIVATE_KEY';
var LAPTOP_RATELIMIT='LAPTOP_RATELIMIT'

// returned after info loaded in GW
var LOADED='LOADED';
	
exports.APIMANAGER = APIMANAGER;
exports.APIMANAGER_PORT = APIMANAGER_PORT;
exports.CONFIGDIR = CONFIGDIR;
exports.DATASTORE_PORT = DATASTORE_PORT;
exports.APIMANAGER_CATALOG = APIMANAGER_CATALOG;
exports.GW_PUBLIC_KEY = GW_PUBLIC_KEY;
exports.GW_PRIVATE_KEY = GW_PRIVATE_KEY;
exports.LAPTOP_RATELIMIT = LAPTOP_RATELIMIT;

exports.LOADED = LOADED;
