
// ENV vars for gateway processing
var APIMANAGER='APIMANAGER';
var APIMANAGER_PORT='APIMANAGER_PORT';
var APIMANAGER_CATALOG='APIMANAGER_CATALOG';

var CONFIGDIR='CONFIG_DIR';
var DATASTORE_PORT='DATASTORE_PORT';

var LAPTOP_RATELIMIT='LAPTOP_RATELIMIT'

// returned after info loaded in GW
var LOADED='LOADED';
	
exports.APIMANAGER = APIMANAGER;
exports.APIMANAGER_PORT = APIMANAGER_PORT;
exports.APIMANAGER_CATALOG = APIMANAGER_CATALOG;

exports.CONFIGDIR = CONFIGDIR;
exports.DATASTORE_PORT = DATASTORE_PORT;

exports.LAPTOP_RATELIMIT = LAPTOP_RATELIMIT;

exports.LOADED = LOADED;
